# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
dist: xenial
repos:
  CRAN: https://cloud.r-project.org
  PIK:  https://rse.pik-potsdam.de/r/packages/
cache: packages
latex: false
pandoc: false
r_packages:
  - lucode
script:
  - Rscript -e "null <- lucode::codeCheck(strict=TRUE)"

